#%RAML 1.0

title: core-api
baseUri: ${baseUri}/${version}
version: v1
mediaType: application/json

/account:
  displayName: Account
  post:
    description: create an account
    body:
      application/json:
        type: |
          {
            "email": {
              "type": "string",
              "required": true
            },
            "password": {
              "type": "string",
              "required": true,
              "description": "max 16 characters"
            },
            "username": {
              "type": "string",
              "required": true,
              "description": "max 16 characters"
            }
          }
    responses:
      201:
        body:
          application/json:
            type: |
              {
                "email": {
                  "type": "boolean",
                  "required": true
                },
                "username": {
                  "type": "boolean",
                  "required": true
                },
                "password": {
                  "type": "boolean",
                  "required": true
                }
              }
      400:
        body:
          application/json:
            type: |
              {
                "email": {
                  "type": "boolean",
                  "required": true
                },
                "username": {
                  "type": "boolean",
                  "required": true
                },
                "password": {
                  "type": "boolean",
                  "required": true
                }
              }
      500:
        body:
          application/json:
            type: |
              {
                "reason": {
                  "type": "string",
                  "required": true
                }
              }

/realm:
  displayName: Realm
  get:
    description: list all realms
    responses:
      200:
        body:
          application/json:
            type: |
              {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number",
                      "required": true
                    },
                    "name": {
                      "type": "string",
                      "required": true
                    },
                    "icon": {
                      "type": "number",
                      "required": true
                    },
                    "timezone": {
                      "type": "number",
                      "required": true
                    },
                    "population": {
                      "type": "number",
                      "required": true
                    }
                  }
                }
              }
      500:
        body:
          application/json:
            type: |
              {
                "reason": {
                  "type": "string",
                  "required": true
                }
              }
